### PR TITLE
commiting GitTest2 into BranchX

### PR DESCRIPTION
**Pull request by OpenRaj**
Hi,

I have committed GitTest2, Please review and approve.

Thanks
Open Raj

### CODE REVIEW

**Comment by SomendraKumar** [comment]
Hi X,

Your code looks good, please add one more condition.

Thank you
Somendra Kumar

**Comment by SomendraKumar** [comment]
Hi X,

I have added additional check please review it.

Thanks
Somendra Kumar

**Comment by OpenRaj** [comment]
Hi,

I have done it, just cross check it sir.

Regards
Somendra Kumar

**Comment by SomendraKumar** [comment]
Hi X,

Your code looks good, just go ahead..

Regards
Somendra Kumar

**Pull request merged**
